---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: green-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: green-deployment
  template:
    metadata:
      labels:
        app: green-deployment
    spec:
      containers:
      - name: green-container
        image: adamtravis/rollouts:green
        ports:
        - name: http
          containerPort: 8080
